name: lg_semseg
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.4=py38hce1f21e_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.6.15=ha878542_0
  - certifi=2022.6.15=py38h578d9bd_0
  - cffi=1.15.0=py38hd667e15_1
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cudatoolkit=11.1.1=ha002fc5_10
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask-core=2022.5.0=py38h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h0708190_1
  - fsspec=2022.3.0=py38h06a4308_0
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.56.2=hd408876_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=he6710b0_3
  - imageio=2.9.0=pyhd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py38h06a4308_0
  - ipython=8.3.0=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=4.4.0=py38h06a4308_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.2.2=py38h06a4308_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.43.0=h7f98852_0
  - libwebp=1.2.0=h89dd481_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.4.4=py38h06a4308_0
  - nbformat=5.3.0=py38h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py38h06a4308_0
  - nettle=3.6=he412f7d_0
  - networkx=2.7.1=pyhd3eb1b0_0
  - ninja=1.11.0=h924138e_0
  - notebook=6.4.11=py38h06a4308_0
  - numexpr=2.8.1=py38h807cd23_2
  - numpy=1.22.3=py38he7a7128_0
  - numpy-base=1.22.3=py38hf524024_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1o=h166bdaf_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.2=py38h295c915_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.1.2=py38h06a4308_0
  - plyfile=0.7.4=pyhd8ed1ab_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.0=py38heee7806_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=py3.8_cuda11.1_cudnn8.0.5_0
  - pytz=2022.1=py38h06a4308_0
  - pywavelets=1.3.0=py38h7f8727e_0
  - pyyaml=6.0=py38h7f8727e_1
  - pyzmq=22.3.0=py38h295c915_2
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - readline=8.1.2=h7f8727e_1
  - scikit-image=0.19.2=py38h51133e4_0
  - scikit-learn=1.0.2=py38h51133e4_1
  - scipy=1.7.3=py38hc147768_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - sip=6.5.1=py38h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.5=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.13.1=py38h06a4308_0
  - testpath=0.6.0=py38h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchvision=0.10.0=py38_cu111
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - trimesh=3.12.8=pyh6c4a22f_0
  - typing_extensions=4.3.0=pyha770c72_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38h06a4308_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=py38h06a4308_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - absl-py==1.2.0
    - addict==2.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.1
    - async-timeout==4.0.2
    - babel==2.10.3
    - cachetools==5.2.0
    - charset-normalizer==2.1.0
    - click==8.1.3
    - colorlog==6.6.0
    - cycler==0.11.0
    - deprecation==2.1.0
    - docker-pycreds==0.4.0
    - fonttools==4.34.4
    - frozenlist==1.3.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - hydra-colorlog==1.2.0
    - hydra-core==1.2.0
    - hydra-submitit-launcher==1.2.0
    - idna==3.3
    - importlib-metadata==4.12.0
    - json5==0.9.8
    - jupyter-packaging==0.12.2
    - jupyter-server==1.18.1
    - jupyterlab==3.4.3
    - jupyterlab-server==2.15.0
    - kiwisolver==1.4.4
    - markdown==3.4.1
    - matplotlib==3.5.2
    - minkowskiengine==0.5.4
    - multidict==6.0.2
    - nbclassic==0.4.3
    - notebook-shim==0.1.0
    - oauthlib==3.2.0
    - omegaconf==2.2.2
    - open3d==0.15.2
    - pathtools==0.1.2
    - pg-op==0.0.0
    - pillow==9.2.0
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pyquaternion==0.9.9
    - pytorch-lightning==1.6.5
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sentry-sdk==1.8.0
    - setproctitle==1.2.3
    - setuptools==59.5.0
    - shortuuid==1.0.9
    - smmap==5.0.0
    - sniffio==1.2.0
    - submitit==1.4.4
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tomlkit==0.11.1
    - torchmetrics==0.9.2
    - tqdm==4.64.0
    - urllib3==1.26.10
    - wandb==0.12.21
    - websocket-client==1.3.3
    - werkzeug==2.1.2
    - yarl==1.7.2
prefix: /home/drozenberszki/anaconda3/envs/lg_semseg
